#!/bin/bash

# Create log directory if it doesn't exist
mkdir -p test_log

# List of map files to be tested
TEST_FILES=$(ls maps/*.ber)

# Loop through each map
for file in $TEST_FILES; do
	# Extract the basename of the file without extension
	base=$(basename "$file" .ber)
	log="test_log/${base}_valgrind.log"

	echo "Running test: $file"
	valgrind --leak-check=full --show-leak-kinds=all --log-file="$log" ./so_long "$file"
	echo "Log saved to $log"
done
