#!/bin/bash

# Create log directory if it doesn't exist
mkdir -p test_bonus_log

# Remove reading permissions for no_perm_bonus.ber
if [ -f maps_bonus/no_perm_bonus.ber ]; then
	chmod -r maps_bonus/no_perm_bonus.ber
else
	echo "Warning: couldn't find maps_bonus/no_perm_bonus.ber"
fi

# Loop through each map
for file in maps_bonus/*.ber; do
	# Extract the basename of the file without extension
	base=$(basename "$file" .ber)
	log="test_bonus_log/${base}_valgrind.log"

	echo "Running test: $file"
	valgrind --leak-check=full --show-leak-kinds=all --log-file="$log" ./so_long_bonus "$file"
	echo "Log saved to $log"
done

# Restore reading permissions to no_perm_bonus.ber so it can be commited
if [ -f maps_bonus/no_perm_bonus.ber ]; then
	chmod +r maps_bonus/no_perm_bonus.ber
else
	echo "Warning: couldn't find maps_bonus/no_perm_bonus.ber"
fi