#!/bin/bash

# Create log directory if it doesn't exist
mkdir -p test_log

#Remove reading permissions for no_perm.ber
if [ -f maps/no_perm.ber ]; then
	chmod -r maps/no_perm.ber
else
	echo "Warning: couldn't find maps/no_perm.ber"
fi

# Loop through each map
for file in maps/*.ber; do
	# Extract the basename of the file without extension
	base=$(basename "$file" .ber)
	log="test_log/${base}_valgrind.log"

	echo "Running test: $file"
	valgrind --leak-check=full --show-leak-kinds=all --log-file="$log" ./so_long "$file"
	echo "Log saved to $log"
done

# Restore reading permission to no_perm.ber so it can be commited
if [ -f maps/no_perm.ber ]; then
	chmod +r maps/no_perm.ber
else
	echo "Warning: couldn't find maps/no_perm.ber"
fi